### ISSUE TITLE
änderungen im childtheme

### ISSUE THREAD

**Issue by wozo** [medizinmedien/top-mod1#2]
es gibt ein paar kleine änderungen für das ht childtheme
- testimonials media query
- logo novartis

@hostz-frank  
bitte, falls von @SimonAlm ok,
um deploy 8954e3b8218c5cf4b0557b9995b1a37a734ff6d6

**Comment by SimonAlm** [comment]
ja bitte deploy, passt

**Comment by hostz-frank** [comment]
> ja bitte deploy, passt

Ist erledigt. Bitte nachtesten.

**Comment by SimonAlm** [comment]
schaut gut aus. Danke.
